### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by mao3329** [mao3329/furima-32525#9]
#URL
https://furima-32525.herokuapp.com/

#BASIC認証のIDとPassword
ID: mari Password: 0730

#出品者用のメールアドレスとパスワード
email: aaa@gmail.com Password: aaaaa1

#購入者用のメールアドレスとパスワード
email: aaaa@gmail.com Password: aaaaa1

#購入用カードの番号・期限・セキュリティコード
number: 4242424242424242
exp: 4/24
cvc: 123

**Comment by naokihayasan127** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。
